# Generated by Django 5.2.4 on 2025-07-23 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Compositor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("fecha_de_nacimiento", models.DateField(blank=True, null=True)),
                ("pais", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Instrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("familia", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Partituras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("genero", models.CharField(max_length=100)),
                ("fecha_creacion", models.DateField(blank=True, null=True)),
                ("editorial", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha_publicacion", models.DateField(blank=True, null=True)),
                ("numero_opus", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "compositor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partitura",
                        to="partiturasApp.compositor",
                    ),
                ),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="partiturasApp.instrumento",
                    ),
                ),
            ],
        ),
    ]
