# Generated by Django 5.2.4 on 2025-07-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partiturasApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Partituras",
            new_name="Partitura",
        ),
    ]
