# Generated by Django 5.2.4 on 2025-07-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partiturasApp", "0002_rename_partituras_partitura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partitura",
            name="compositor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partituras",
                to="partiturasApp.compositor",
            ),
        ),
        migrations.AlterField(
            model_name="partitura",
            name="instrumento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instrumentos",
                to="partiturasApp.instrumento",
            ),
        ),
    ]
