# Generated by Django 5.2.4 on 2025-07-25 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "partiturasApp",
            "0004_rename_fecha_creacion_partitura_fecha_creacion_partitura_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compositor",
            name="fecha_ingreso",
        ),
        migrations.RemoveField(
            model_name="instrumento",
            name="fecha_ingreso",
        ),
    ]
