# Generated by Django 5.2.4 on 2025-07-27 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partiturasApp", "0005_remove_compositor_fecha_ingreso_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ALGO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                (
                    "Compositor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compositor",
                        to="partiturasApp.compositor",
                    ),
                ),
            ],
        ),
    ]
