# Generated by Django 5.2.4 on 2025-07-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partiturasApp", "0006_algo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ALGO",
            new_name="PRUEBA",
        ),
        migrations.AlterField(
            model_name="partitura",
            name="genero",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
