# Generated by Django 5.2.4 on 2025-07-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partiturasApp", "0007_rename_algo_prueba_alter_partitura_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partitura",
            name="genero",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
