# Generated by Django 5.2.4 on 2025-07-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partiturasApp", "0008_alter_partitura_genero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("epoca_principal", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="partitura",
            name="genero",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
