# Generated by Django 5.2.4 on 2025-07-29 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partiturasApp', '0009_genero_alter_partitura_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='Compositor',
            new_name='compositor',
        ),
    ]
