# Generated by Django 5.2.4 on 2025-08-08 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partiturasApp', '0010_rename_compositor_prueba_compositor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partitura',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
