# Generated by Django 5.2.5 on 2025-08-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partiturasApp', '0011_rename_titulo_partitura_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PRUEBA',
        ),
    ]
